import type { Convention, Dimension, Severity } from '../../../config/types.js';
import type { ExportFormatter } from './types.js';

const SEVERITY_ICONS: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🟢',
};

const DIMENSION_TITLES: Record<Dimension, string> = {
  naming: 'Naming Conventions',
  structure: 'Project Structure',
  component: 'Component Patterns',
  testing: 'Testing Standards',
  'error-handling': 'Error Handling',
  imports: 'Import Conventions',
  git: 'Git Conventions',
  state: 'State Management',
  api: 'API Patterns',
};

export class ClaudeFormatter implements ExportFormatter {
  readonly filename = 'CLAUDE.md';
  readonly targetDir = '.';

  format(conventions: Convention[]): string {
    const lines: string[] = [
      '# Project Conventions',
      '',
      'This file was auto-generated by CodePlug. It describes the coding conventions detected in this project.',
      '',
    ];

    const grouped = this.groupByDimension(conventions);

    for (const [dimension, items] of grouped) {
      lines.push(`## ${DIMENSION_TITLES[dimension] ?? dimension}`);
      lines.push('');

      const sorted = [...items].sort((a, b) => severityRank(a.severity) - severityRank(b.severity));

      for (const conv of sorted) {
        lines.push(`- ${SEVERITY_ICONS[conv.severity]} **[${conv.severity.toUpperCase()}]** ${conv.rule}`);
        if (conv.examples.length > 0) {
          lines.push(`  - Examples: ${conv.examples.slice(0, 3).map(e => `\`${e}\``).join(', ')}`);
        }
      }

      lines.push('');
    }

    lines.push('---');
    lines.push(`_Generated by CodePlug on ${new Date().toISOString().split('T')[0]}_`);
    lines.push('');

    return lines.join('\n');
  }

  private groupByDimension(conventions: Convention[]): Map<Dimension, Convention[]> {
    const map = new Map<Dimension, Convention[]>();
    for (const c of conventions) {
      const list = map.get(c.dimension) ?? [];
      list.push(c);
      map.set(c.dimension, list);
    }
    return map;
  }
}

function severityRank(s: Severity): number {
  const order: Record<Severity, number> = { critical: 0, high: 1, medium: 2, low: 3 };
  return order[s];
}
